### ISSUE TITLE
Request for rotation props

### ISSUE THREAD

**Issue by ayepRahman** [ricardo-ch/react-easy-crop#47] opened 2019-07-10 06:36 UTC
## Are you making a feature request?

- Is there a plan on making the image rotatable?

**Comment by ValentinH** [comment] 2019-07-10 06:38
I've never thought about this but I don't think so. On ricardo.ch, we have a simple to rotate the image by 90°.

**Comment by Junbong** [comment] 2019-07-10 07:06
> ## Are you making a feature request?
> * Is there a plan on making the image rotatable?

I like this idea.

**Comment by ValentinH** [comment] 2019-07-12 05:37
How would you see this feature? What would be the UI?

**Comment by ayepRahman** [comment] 2019-07-12 05:41
Probably pass props of integer in degree 90 etc

**Comment by ValentinH** [comment] 2019-07-12 05:43
I edited my previous answer.

The API would be quite simple indeed: `rotation: number` and `onRotationChange: number => void`.

Any thoughts regarding UI?

**Comment by ValentinH** [comment] 2019-07-12 05:44
Actually it could be started with only an external UI for desktop (like a slider), and handle the rotation on mobile within the library.

**Comment by ayepRahman** [comment] 2019-07-12 05:46
I like using components from Mui. But anyone can use any JSX element with
onClick function to handle the roration. Even slider from Mui which
previosuly you shown. Maybe you can ref the edit photo in LinkedIn?

**Comment by ValentinH** [comment] 2019-07-12 05:57
OK, for now, I'll add support for the `rotation` prop, this is easy. I'll see later if we should add mobile gesture to handle this within the component 🙂

**Comment by ValentinH** [comment] 2019-07-12 06:02
Wow, I didn't see this LinkedIn feature, the cropper element looks exactly like this one! I will do a demo to show how to build this UI with `react-easy-crop`😎

![image](https://user-images.githubusercontent.com/2678610/61105815-51187200-a47b-11e9-905f-24fbc27b7fa9.png)

**Comment by ValentinH** [comment] 2019-07-12 06:33
Support added for `rotation` prop in v1.14.0: https://github.com/ricardo-ch/react-easy-crop/releases/tag/v1.14.0 🎉
I've updated the website demo: https://ricardo-ch.github.io/react-easy-crop/ 🙂

**Comment by ayepRahman** [comment] 2019-07-12 06:41
Woah that was fast. Great job Valentin!

**Comment by ValentinH** [comment] 2019-07-15 06:23
@ayepRahman supporting the rotation in the "Show results" popup is more tricky than expected. For now, I've removed it from the demo and marked the rotation as "experimental" in the ReadMe.
Did you actually managed to use this new `rotation` prop? If yes, do you then generate the output image within the browser (canvas)?

**Comment by rafaelsorto** [comment] 2019-07-19 05:10
This is amazing, I was about to fork the repo and see if I could get something like rotation rolling. I'll test the one that you added and come back with comments. Thank you for adding something like this. It's quite expected nowadays to just do pinch and zoom/rotate on mobile.

**Comment by ValentinH** [comment] 2019-07-19 06:42
For now, we don't support rotating the image with gestures. I'd like to first ensure that the way rotation is handled now is correct:
- is the data exported by the lib enough to actually crop/rotate the original image? The `croppedAreaPixels` data might be wrong when rotation is different than 0.
- the "show output" demo should handled the rotation.
- what about edges detection? Right now, it's acting like the rotation is 0 which might not be the right approach.

Any help is welcome here because as I don't use the rotation myself, I might not be the right person to define those requirements.

**Comment by MattyBalaam** [comment] 2019-08-16 16:25
I’ve been having a little play with the rotation, but I’m hitting a wall trying to convert the co-ordinates to something that canvas will translate accurately. 

If the crop is dead-center then using this kind of technique appears to work fine:

```      context.translate(
        croppedAreaPixels.width / 2,
        croppedAreaPixels.height / 2,
      );

      context.rotate(getRadianAngle(rotation));

      context.translate(
        -croppedAreaPixels.width / 2,
        -croppedAreaPixels.height / 2,
      );

    context.drawImage(
      image,
      croppedAreaPixels.x,
      croppedAreaPixels.y,
      image.width,
      image.height,
      0,
      0,
      image.width, 
      image.height,
    );

```

However once the image is moved away from a central position then the image is moved in the wrong position and I just don’t have the knowledge about how to translating these x/y values.

**Comment by ValentinH** [comment] 2019-08-16 16:27
@MattyBalaam Indeed, I faced the same issue. Everything goes wrong once the image is moved from the center. Also the edge detection is broken.

**Comment by MattyBalaam** [comment] 2019-08-16 16:32
I’ll invest some time next week investigating this a bit further.

**Comment by MattyBalaam** [comment] 2019-08-17 14:52
Thinking out loud... I wonder if a way to do it might be for having a canvas the size of the original image, the context to the rotated, then the image applied without cropping. The initial context should then be restored and then the result of this can then be cropped.

**Comment by ValentinH** [comment] 2019-08-17 15:12
When do you translate the image if needed?

**Comment by MattyBalaam** [comment] 2019-08-17 16:34
So after the rotation is applied the image is drawn with scaling, but not cropped. The cropping would be done afterwards. I'm thinking out loud without a laptop so this might not work how I imagine. But my thinking is that doing it this way will simulate more what is happening in the css transformation.

**Comment by MattyBalaam** [comment] 2019-08-17 16:35
There is no doubt a more mathematical algorithm approach to doing this of course.

**Comment by ValentinH** [comment] 2019-08-17 16:38
This is my main issue, I'm too lazy to do proper maths. Most of this library mathematical computations have been implemented by bruteforcing some formulas! 😃

**Comment by mbalaam** [comment] 2019-08-19 08:55
So, I can confirm that this approach creates a crop that matches the preview. However at the moment as you mention the problem is that the edge detection is broken.

I’ll for the code sandbox with some working code later today.

**Comment by ValentinH** [comment] 2019-08-19 08:58
This is awesome, it would be really nice to have a working example with the image export when rotation! We can deal with the edge detection later.

**Comment by mbalaam** [comment] 2019-08-19 12:06
Here is a forked demo with rotation preview: https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-mlwif?fontsize=14

**Comment by ValentinH** [comment] 2019-08-19 12:17
MAN!

![genius](https://media1.giphy.com/media/5FoxedYWNVmO4/giphy.gif?cid=790b7611238c7806fd58eb053066091bb3d78b1889853c10&rid=giphy.gif)

This is so cool! Would you like to make a PR on the demo website to showcase this? Basically, [this block](https://github.com/ricardo-ch/react-easy-crop/commit/2fd0e736a3a6dd2bda82b59d12696dbb02777734#diff-53a3f5977277f82e803595cdaa02fc76R105) should be uncommented, and you `rotateImage()` should be added.

Just one question, do you think there is a way to do the rotation and the crop/translate on the same canvas so that we only generate one image?

**Comment by mbalaam** [comment] 2019-08-19 12:57
I’ve had a rethink, and here is an improved v2: https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-pd4v5

**Comment by ValentinH** [comment] 2019-08-19 13:17
The code looks great! However, something might have been wrong because the output modal doesn't open anymore.

**Comment by mbalaam** [comment] 2019-08-19 13:22
In the PR? I should have run it, I’ll check

**Comment by ValentinH** [comment] 2019-08-19 13:23
No I meant in the sandbox

**Comment by mbalaam** [comment] 2019-08-19 13:25
It’s working here. I’ve resaved it just in case.

**Comment by ValentinH** [comment] 2019-08-19 13:33
Yes nevermind, it was due to my browser (Brave) tracking prevention.

**Comment by ValentinH** [comment] 2019-08-19 14:22
Thanks to @mbalaam, the demo now supports the rotation props! 🎉 

This mean that the only last remaining thing in the initial todo list is the edge detection. I think we can already remove the "experimental" flag from the readme as this is not that bad.

**Comment by ValentinH** [comment] 2019-08-19 14:35
I'm closing this issue now. I have opened #52 for the edge detection.

**Closed** 2019-08-19 15:07 UTC
Labels: enhancement

**Comment by marvwhere** [comment] 2019-09-12 07:38
Question: The "Show Image" is still not showing the right position, if you rotate and leave the center, right? 

I tested with the above v2 codesandbox 

Is there any solution for it?

**Comment by ValentinH** [comment] 2019-09-22 14:53
I've found and fixed the issue locally. I'm adding some tests and publishing a fix soon 🎉

**Comment by MattyBalaam** [comment] 2019-09-22 15:01
That's awesome news. Been really busy over the last couple of weeks and unable to find the time to investigate.

**Comment by ValentinH** [comment] 2019-09-22 15:02
If you want to have a look: #63

**Comment by ValentinH** [comment] 2019-09-22 15:38
A fix has been published under 1.16.1. I've also updated the demo website and this sandbox: https://codesandbox.io/s/q8q1mnr01w.

**Comment by mbalaam** [comment] 2019-10-07 12:47
I’ve found some time to look at this as the demo was still showing the issue. 

Good news is I think I know how to fix the canvas code and will open a PR. The clipping is happening because even though I am rotating on a canvas twice the size of the original image, once the crop is rotated around 90 degrees and then moved to an extreme edge the image is still clipped.

**Comment by ValentinH** [comment] 2019-10-07 12:49
Indeed, in some really edge cases, a small part of the image can be clipped. 🙂

**Comment by mbalaam** [comment] 2019-10-07 14:14
OK, I’m now generating the 'safe area' for the rotation based around the maximum width or height, so as far as I can tell the clipping issue is fixed now. Does anyone fancy giving it a battle test?

https://o87hi.csb.app/

**Comment by ValentinH** [comment] 2019-10-07 15:04
I only see a black output when clicking the "Show results" button 😄

**Comment by mbalaam** [comment] 2019-10-07 15:28
Hmmm, code sandbox doesn’t seem to have the right version saved going back to it… I’m going to need to work it out again

**Comment by mbalaam** [comment] 2019-10-07 15:57
Fingers crossed it will work this time…

https://codesandbox.io/embed/react-easy-crop-demo-with-cropped-output-o87hi

just in case though…

```

  const safeArea = Math.max(image.width, image.height) * 2

  // set width to double image size to allow for a safe area for the
  // image to rotate in without being clipped by canvas context
  canvas.width = safeArea
  canvas.height = safeArea

  // translate canvas context to a central location on image to allow rotating around the center.
  ctx.translate(safeArea / 2, safeArea / 2)
  ctx.rotate(getRadianAngle(rotation))
  ctx.translate(-safeArea / 2, -safeArea / 2)

  // draw rotated image and store data.
  ctx.drawImage(
    image,
    safeArea / 2 - image.width * 0.5,
    safeArea / 2 - image.height * 0.5
  )
  const data = ctx.getImageData(0, 0, safeArea, safeArea)

  // set canvas width to final desired crop size - this will clear existing context
  canvas.width = pixelCrop.width
  canvas.height = pixelCrop.height

  // paste generated rotate image with correct offsets for x,y crop values.
  ctx.putImageData(
    data,
    0 - safeArea / 2 + image.width * 0.5 - pixelCrop.x,
    0 - safeArea / 2 + image.height * 0.5 - pixelCrop.y
  )
```

**Comment by ValentinH** [comment] 2019-10-08 06:14
Indeed, it looks much better now! Would you like to update the website demo code? I'll update the sandboxes :)

**Comment by ValentinH** [comment] 2019-10-08 06:19
@all-contributors please add @mbalaam for doc

**Comment by StefanZivkovic** [comment] 2020-04-29 13:18
Hi guys,

I see you have rotation slider feature. Do you have built-in button-icon for left/right 90 degrees rotation? If not, any known suggestions how to implement it?

**Comment by ValentinH** [comment] 2020-04-29 13:34
Hi,

No there is no built-in feature for this but you can achieve it quite easily. Here's an example: https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-03rzb

**Comment by StefanZivkovic** [comment] 2020-04-29 13:42
Ok, 

Good, i implemented same way, but was curious if there are some other Cropper related props to use for this purposes.

Thank you @ValentinH for effort and quick response.

**Comment by shiva15102012** [comment] 2020-09-19 22:05
Hi,

I went through the entire code and it's working fine in chrome browser but in the safari browser it's showing only a small area of the image even if I manually updated with initialCroppedAreaPixels.

And one more issue if we open this code in ios device safari and showing the black screen always if we upload the large size of image so I fixed the size issue with compress code but initialCroppedAreaPixels is always small when I opened in the ios safari browser.

Can some help me to fix the issue with initialCroppedAreaPixels in ios safari browser

**Comment by ValentinH** [comment] 2020-09-20 01:15
Please open a new issue with a reproduction example. I don't see what's the link with this issue.
