### ISSUE TITLE
Grid not moving

### ISSUE THREAD

**Issue by shaheryarJS** [ricardo-ch/react-easy-crop#222] opened 2021-03-24 12:08 UTC
-**Describe the bug**
I have a basic cropper setup and it works as expected when I don't scroll the grid. But when I do, the grid doesn't visually move and returns error:  
TypeError: Failed to execute 'putImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.  
because of the position being:  
{width: 1000, height: 1000, x: NaN, y: NaN}  
  
for some reason the position is not a number.

**To Reproduce**
react code:  
`      <div style={{height: '90%', padding: 10}}>  

        <div style={{ height: '90%', position: 'relative' }}>  

          <Cropper
            restrictPosition={false}
            image={image}
            aspect={1}
            crop={crop}
            zoom={zoom}
            onCropChange={cropChange}
            onZoomChange={zoomChange}
            onCropComplete={onCropComplete}
          />  

        </div>  

        <div style={{height: '10%', width: '60vw', display: 'flex', alignItems: 'center', margin: 'auto'}}>  

          <Slider
            min={1} max={3}
            step={0.1}
            value={zoom}
            onChange={(e, zoom) => setZoom(zoom)}
          />  

          <IonButton onClick={() => getCroppedImg(image, croppedPixels)}>
            Complete
          </IonButton>  

          <IonButton  

            onClick={() => {  

              setImage({ 
                src: permPic, 
                alt: "Profile pic" });  

              setFileSelected(false);  
            }}
          >
            Cancel
          </IonButton>    

        </div>`

**Expected behavior**
I want the grid to be able to move and return a number for the x and y positions.

**Comment by ValentinH** [comment] 2021-03-24 17:28
I'm not sure I get what you mean with "When I scroll the grid". Could you please provide a codesandbox where I could reproduce the issue?

**Comment by ValentinH** [comment] 2021-04-19 12:48
Closing as there was no answer for a while. Comment to re-open 😉

**Closed by ValentinH** 2021-04-19 12:48 UTC
Labels: need-reproduction

**Comment by adammo94** [comment] 2021-04-23 11:26
I have the very same problem.

```
<Cropper
  image={'https://www.pozycjonusz.pl/wp-content/uploads/2018/05/url.png'}
  crop={crop}
  zoom={zoom}
  onCropChange={(newCrop) => { console.log(newCrop); setCrop({ newCrop }) }}
  onZoomChange={(newZoom) => setZoom({ zoom })}
  aspect={4 / 3}
/>
```

wrapper for cropper has this css attributes:
```
display: flex;
flex-direction: column;
position: relative;
border-radius: 9px;
max-height: 480px;
overflow: hidden;
min-height: 267px;
```

I can't move the cropping grid, it just stays in the same spot and console.log(newCrop) from onCropChange gives: `{x: NaN, y: NaN}`

**Comment by ValentinH** [comment] 2021-04-23 11:38
Please share a codesandbox showing the issue.
I cannot tell you what's wrong just by looking at this.
Just a guess: the `setCrop({ newCrop })` call looks suspicious to me. If `setCrop` is a useState setter, it should be `setCrop(newCrop)` (same for `setZoom()`).

**Comment by adammo94** [comment] 2021-04-23 11:41
That solved the issue, I used {newCrop} because it wass in documentation, however I overlooked that's for the class components :p

**Comment by ValentinH** [comment] 2021-04-23 11:46
What documentation are you referring too please? Maybe we could improve it 🙂

**Comment by adammo94** [comment] 2021-04-23 11:56
I'm reffering to basic usage section. Maybe you just could add another example with use of functional component :D

**Comment by ValentinH** [comment] 2021-04-23 11:58
I actually converted it to use hooks a few weeks ago, are you looking at the `main` version?
![image](https://user-images.githubusercontent.com/2678610/115867873-e8c23700-a43b-11eb-8f02-c8d0f7a4458f.png)

**Comment by ValentinH** [comment] 2021-04-23 11:59
Maybe you are reading the Readme from NPM. Indeed, I didn't push a new version for that change, let's me do that.

**Comment by ValentinH** [comment] 2021-04-23 12:02
3.3.3 fixes it. It will take a few minutes before being updated on https://www.npmjs.com/package/react-easy-crop probably.

**Comment by adammo94** [comment] 2021-04-23 12:25
Yeah, I was looking at npm version. Many thanks man, have a good day

**Comment by Chetanr** [comment] 2021-09-07 05:31
Hi,
I am trying to show the cropper using a button onClick event. But the grid is not showing up. Below is the code

`function ChooseImage({ location }) {
  const classes = useStyles();
  const history = useHistory();
  const [selectedFile, setSelectedFile] = useState(null);
  const [visibility, setVisibility] = useState(true);
  const [alert, setAlert] = useState(null);

  const [crop, setCrop] = useState({ x: 1, y: 1 });
  const rotation = useState(0);
  const [zoom, setZoom] = useState(1);
  const [croppedAreaPixels, setCroppedAreaPixels] = useState(null);
  const [cropperVisibility, setCropperVisibility] = useState(false);
  const [doneVisibility, setDoneVisibility] = useState(false);
  const [cropVisibility, setCropVisibility] = useState(false);

  const onCropComplete = useCallback((croppedArea, croppedAreaPixels) => {
    setCroppedAreaPixels(croppedAreaPixels);
  }, []);

  const showCroppedImage = useCallback(async () => {
    try {
      const croppedImage = await getCroppedImg(
        selectedFile,
        croppedAreaPixels,
        rotation
      );
      setVisibility(true);
      setCropperVisibility(false);
      setDoneVisibility(false);
      setSelectedFile(croppedImage);
    } catch (e) {
      console.error(e);
    }
  }, [croppedAreaPixels, rotation, selectedFile]);

  const changeHandler = (event) => {
    setSelectedFile(URL.createObjectURL(event.target.files[0]));
    setCropVisibility(true);
    // setVisibility(false);
  };

  const checkImageSelection = (event) => {
    selectedFile === null
      ? setAlert(<Alert data="Please select an image and then proceed!" />)
      : renderNext();
  };

  const showCropper = () => {
    setVisibility(false);
    setCropperVisibility(true);
    setCropVisibility(false);
    setDoneVisibility(true);
  };

  const renderNext = () => {
    sessionStorage.setItem("croppedImage", selectedFile);
    let img = new Image();
    img.src = selectedFile;
    img.onload = () => {
      console.log(img.width + " " + img.height);
      sessionStorage.setItem("ImgWidth", img.width);
      sessionStorage.setItem("ImgHeight", img.height);
      if (img.width > img.height) {
        sessionStorage.setItem("Shorter Side", img.height);
        sessionStorage.setItem("Longer Side", img.width);
      } else {
        sessionStorage.setItem("Shorter Side", img.width);
        sessionStorage.setItem("Longer Side", img.height);
      }
    };

    sessionStorage.setItem(
      "height",
      Math.round(
        (sessionStorage.getItem("Shorter Side") * constants.pic_w) /
          sessionStorage.getItem("ImgWidth")
      )
    );

    history.push("/ImageSize", { from: "ChooseImage" });
  };

  return (
    <div className={classes.root}>
      <Header />
      <h1 className={classes.text}>Choose Your Image</h1>
      <Box className={classes.cardBox}>
        <div
          style={{
            display: visibility && selectedFile === null ? "block" : "none",
          }}
        >
          <Card className={classes.card}>
            <CardActionArea>
              <CardContent className={classes.cardContent}>
                <Typography className={classes.cardTitle}>
                  Max Size: 30MB
                </Typography>
              </CardContent>
              <CardContent className={classes.cardContent}>
                <Typography className={classes.cardBody}>
                  Supported Files: JPG, JPEG, PNG
                </Typography>
              </CardContent>
              <CardActions className={classes.cardContent}>
                <div>
                  <input
                    accept="image/jpg, image/jpeg, image/png "
                    className={classes.input}
                    id="contained-button-file"
                    type="file"
                    onChange={changeHandler}
                  />
                  <label htmlFor="contained-button-file">
                    <Button
                      variant="contained"
                      className={classes.UploadButton}
                      component="span"
                    >
                      Upload
                    </Button>
                  </label>
                </div>
              </CardActions>
            </CardActionArea>
          </Card>
        </div>
        <div
          className={classes.card}
          style={{
            display: cropperVisibility ? "block" : "none",
          }}
        >
          <div className={classes.card}>
            <Cropper
              minZoom="0.4"
              image={selectedFile}
              crop={crop}
              zoom={zoom}
              aspect={4 / 3}
              // restrictPosition={true}
              objectFit="contain"
              onCropChange={(newCrop) => {
                setCrop(newCrop);
              }}
              onCropComplete={onCropComplete}
              onZoomChange={setZoom}
              // className={classes.card}
            />
          </div>
        </div>
        <div
          className={classes.card}
          style={{
            display: selectedFile === null ? "none" : "block",
          }}
        >
          <div className={classes.card}>
            <img src={selectedFile} aria-hidden alt={"image"} />
          </div>
        </div>
      </Box>
      <Box className={classes.buttonBox}>
        <Back />
        <Button
          style={{
            display: cropVisibility ? "block" : "none",
          }}
          onClick={showCropper}
          className={classes.NextButton}
        >
          Crop
        </Button>
        <Button
          style={{
            display: visibility ? "block" : "none",
          }}
          onClick={checkImageSelection}
          className={classes.NextButton}
        >
          Next
        </Button>
        <Button
          style={{
            display: doneVisibility ? "block" : "none",
          }}
          onClick={showCroppedImage}
          className={classes.NextButton}
        >
          Done
        </Button>
      </Box>
      {alert}
    </div>
  );
}

export default ChooseImage;`

I am using the latest (3.5.2) npm library. 

Can you please help me with where I am going wrong?

**Comment by Chetanr** [comment] 2021-09-07 05:36
Hi,
I am trying to show the cropper on a button click but the grid is not showing up. Can you please help me?

I am using the latest (3.5.2) version of npm in my code.

I have also attached the text file of the code


[code.txt](https://github.com/ricardo-ch/react-easy-crop/files/7119138/code.txt)

**Comment by ValentinH** [comment] 2021-09-07 08:48
@Chetanr please open a new issue with a codesandbox showing the problem. I don't want to open any random file on my computer.

**Comment by Chetanr** [comment] 2021-09-07 09:12
Hey,
I have created a new issue with the codesandbox link. Please have a look.

*Thanks and Regards,*
*Chetan Revappa*
*Linkedin: *https://www.linkedin.com/in/chetan-r/
