### ISSUE TITLE
Bug in Safari

### ISSUE THREAD

**Issue by alenssy** [ricardo-ch/react-easy-crop#311] opened 2021-11-17 11:27 UTC
Bug only in Safari 15:
- Initially, when uploading video to cropper, it is not displayed
- When there is a picture in the cropper and you change it to the video - it is not displayed, if you change the video to video, then everything works fine.

**Comment by ValentinH** [comment] 2021-11-17 11:51
Could you please create a codesandbox showing the issue please?

**Comment by alenssy** [comment] 2021-11-17 12:23
https://codesandbox.io/s/young-microservice-gidiu

**Comment by ValentinH** [comment] 2021-11-22 20:21
I just opened your sandbox in Safari and I don't notice any issue. Could you please describe a bit more how to see the issue or provide a sandbox directly showing what is wrong?

**Comment by alenssy** [comment] 2021-11-23 20:30
I apologize for your wasted time. This bug occurred in our application, not in your library. I close this issue

**Comment by alexsprings** [comment] 2021-11-23 21:31
Hey @ValentinH 

I have Safari 15.0 running on MacOS 11.6
When I open sandbox in Safari I can't see the video preview in Cropper but I can see it as a plain video HTML element.
![image](https://user-images.githubusercontent.com/5611460/143132229-9a5bb1e4-c567-4f32-9559-01704db4ae24.png)

But when I open the same link in Chrome I can see both videos:
![image](https://user-images.githubusercontent.com/5611460/143132418-38949b44-e67a-4325-bedf-be5a742438c4.png)

**Comment by alenssy** [comment] 2021-11-23 21:37
updated sandbox https://codesandbox.io/s/young-microservice-gidiu?file=/src/App.js

**Comment by ValentinH** [comment] 2021-11-24 19:01
Unfortunately I'm still on Big Sur so I have Safari 14.1. Indeed, there is no issue there.

On Safari 15, do you see any issues in the console?

**Comment by alexsprings** [comment] 2021-11-25 01:21
No, nothing related in the console. And yes for me it works well on Safari 14 as well. The issue is only for 15.

**Comment by trurl-master** [comment] 2021-11-30 11:30
Just tried it in Safari 15.1 - seems to work fine

**Comment by ValentinH** [comment] 2021-11-30 14:14
@alexsprings could you confirm that the issue is fixed on Safari 15.1? It might also be the latest 4.0.0 version released yesterday that fixed it.

**Comment by alexsprings** [comment] 2021-12-01 01:16
@ValentinH We just upgraded to 4.0.0 and I don't see a bug anymore! Thank you for your help!

**Closed** 2021-12-01 02:45 UTC
Labels: bug
