### ISSUE TITLE
Adding the image dynamically and cropping it.

### ISSUE THREAD

**Issue by arunkumaranke-kaaylabs** [ricardo-ch/react-easy-crop#255] opened 2021-05-27 07:44 UTC
Need assistance while dynamically adding the picture and cropping it.

**Comment by ValentinH** [comment] 2021-05-27 09:12
Please add more details, I can help you with what you shared.
Also there are already plenty of examples and one of them allow the user to pick an image from their disk.

**Comment by arunkumaranke-kaaylabs** [comment] 2021-05-27 09:15
Cropper accepts image prop which is an static one, i need to be dynamically select the image from the local storage and crop it accordingly.

**Comment by arunkumaranke-kaaylabs** [comment] 2021-05-27 09:18
There should be an option to upload the desirable image of user's choice and the uploaded image must be cropped. Atlast, cropped image must be returned as object(blob).

**Comment by ValentinH** [comment] 2021-05-27 09:18
https://codesandbox.io/s/y09komm059

**Comment by arunkumaranke-kaaylabs** [comment] 2021-05-27 09:30
![image](https://user-images.githubusercontent.com/76166238/119802536-3ed34000-befc-11eb-9bb6-aa1d205c016a.png)

**Comment by arunkumaranke-kaaylabs** [comment] 2021-05-27 09:30
i need the cropped image in object format.

**Comment by ValentinH** [comment] 2021-05-27 09:51
I'm closing this issue for multiple reasons:
- this is not an issue but a support request. Please use Stackoverflow for such requests.
- you are not following the issue template
- you are not providing enough information

**Closed by ValentinH** 2021-05-27 09:51 UTC

**Comment by btahir** [comment] 2021-05-31 04:00
Apologies if you have already addressed this somewhere else but has there been any issues with this flow based on state lifecycle?

I'm having this weird error where the crop area is not rendered (or maybe is hidden the gray background) if I load an image hidden in a modal which I then show on a click. This does not happen if the modal is open and when the page is first loaded.
I hacked this by setting the modal to be opened and then setting it closed in useEffect. But then it limits my other functionalities such as dynamically changing the image (running into the same problem).

**Comment by ValentinH** [comment] 2021-05-31 09:35
Please provide a codesandbox showing the issue, without it I cannot guess what the problem is.
