### ISSUE TITLE
Image is appearing as black image if I upload image on Iphone

### ISSUE THREAD

**Issue by iamrekhaverma** [ricardo-ch/react-easy-crop#275] opened 2021-07-15 10:42 UTC
**Describe the bug**

**To Reproduce**
https://codesandbox.io/s/y09komm059
Upload photo from iphone and see result. resultant image is coming as black image.

**Expected behavior**
Uploaded image should be visible properly

**Comment by ValentinH** [comment] 2021-07-15 18:38
Duplicate of many issues regarding ios and black output. Please use the search tool.

**Closed by ValentinH** 2021-07-15 18:38 UTC
