### ISSUE TITLE
Cropping iPhone picture returns Black image

### ISSUE THREAD

**Issue by gamecraftCZ** [ricardo-ch/react-easy-crop#164] opened 2020-08-11 19:45 UTC
## Are you reporting a bug? YES

- Problem is observed on [Example with image selected by the user (+ auto-rotation for phone pictures)](https://codesandbox.io/s/y09komm059)

- Provide the steps to reproduce the issue, e.g.:

  1.  Upload image from iPhone camera
  2.  Show result

  **Observed behaviour:** The result is black

  **Expected behaviour:** Cropped image should be shown

![File](https://user-images.githubusercontent.com/11137519/89941847-ea383000-dc1b-11ea-8fa8-fb64368f17b5.jpg)
![File](https://user-images.githubusercontent.com/11137519/89941606-8b72b680-dc1b-11ea-9f7a-07cd7307c265.jpg)

**Comment by ValentinH** [comment] 2020-08-11 20:04
Please look for similar issues before creating a new one.

This is a duplicate of #91, #147 and #98.

**Closed by ValentinH** 2020-08-11 20:04 UTC
