### ISSUE TITLE
The initial crop size is small in Safari

### ISSUE THREAD

**Issue by karlomabunga** [ricardo-ch/react-easy-crop#211] opened 2021-03-07 14:59 UTC
Upon loading, the crop size is smaller in safari compared to other browsers. After checking, the problem seems to be in the function **computeSizes** -> **getBoundingClientRect()** has an issue in safari (the values that it gets on initial load are wrong, but after resizing the screen it finally gets the correct values).

Below is the screenshot that I took in safari:
<img width="525" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/64824524/110243457-67027100-7f95-11eb-8bf2-5843f589f4cd.png">

This is the screenshot that I took using other browser:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/64824524/110243551-d9735100-7f95-11eb-85c3-4cbd0398cdc4.png">

This is the screenshot of the code:
<img width="839" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/64824524/110243860-2d326a00-7f97-11eb-9c66-fe9489ff9237.png">

Any suggestions on how to fix this issue? Thank you.

**Comment by ValentinH** [comment] 2021-03-07 16:44
Are you able to reproduce this issue with the demo or the examples listed on the Readme?
I tried on my machine and they are fine in Safari 🤔 

What version of Safari are you using?

**Comment by karlomabunga** [comment] 2021-03-08 01:24
I wasn't able to reproduce this issue using the demo, but here is how I used the cropper:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/64824524/110262766-ac538c80-7fef-11eb-8625-b40808a400ea.png">

I also tried setting a fixed width and height of the classes 'crop-container' and 'reactEasyCrop_Container' hoping to solve the issue but it still persists.

**Comment by ValentinH** [comment] 2021-03-08 07:15
One thing that catches my eye is the ternary in the image prop. Could you try to do the ternary around the whole cropper?

If it doesn't solve it, could you please create a sandbox reproducing the issue?

**Comment by karlomabunga** [comment] 2021-03-08 13:37
I tried doing the ternary for the image and aspect on the whole cropper but the result is still the same. This is weird because this only occurs in safari and not in the other browsers. I added console logs in the **computeSizes function**, the only problem that I see is that the ** getBoundingClientRect()** returns wrong value on initial load -> I tried adding a timeout(500) in getting the value of **getBoundingClientRect()** and it worked but this affects the experience of the user. Any idea on how to solve this or any idea why is this only occurs in safari?

I will try to reproduce the issue on sandbox, just not sure when I can do it. Thank you.

**Comment by ValentinH** [comment] 2021-03-08 13:43
Without seeing the issue, I cannot help much except by trying to guess. Please ping me when you have a sandbox ready. 🙂

**Comment by ValentinH** [comment] 2021-03-19 14:31
Closing as there was no answer for a while. Comment to re-open 😉

**Closed by ValentinH** 2021-03-19 14:31 UTC
Labels: need-reproduction

**Comment by Dan-Wich** [comment] 2021-12-25 01:55
I had similar symptoms in Safari, so for anyone else noticing these kinds of issues, one thing to check is any size-related CSS animations / transitions that are in progress while the image is loading. If the image loading completes before the animation does, react-easy-crop calls getBoundingClientRect() and receives the size the element occupies during that part of the animation, not the final size. And since it doesn't know about the animation, it doesn't update to the correct size until the window resize event triggers computeSizes again.

**Comment by ValentinH** [comment] 2021-12-25 08:03
Yes this is completely right!
