### ISSUE TITLE
Problem with importing `react-easy-crop` to a TypeScript project

### ISSUE THREAD

**Issue by NastiaPev** [ricardo-ch/react-easy-crop#250] opened 2021-05-13 17:06 UTC
**Describe the bug** 

I keep getting this error when trying to use the component

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function
(for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in,
 or you might have mixed up default and named imports. Check the render method of `SummaryTab`.
```

**To Reproduce**

After installing the react-easy-crop my package.json got "react-easy-crop": "^3.3.3" in the dependencies. So far so good.

I import the Cropper using
` import Cropper from `'react-easy-crop';`

I then try to use the cropper as follows:

```
	<div className="crop-container">
				<Cropper
					image="https://img.huffingtonpost.com/asset/5ab4d4ac2000007d06eb2c56.jpeg?cache=sih0jwle4e&ops=1910_1000"
					crop={crop}
					onCropChange={setCrop}
					disableAutomaticStylesInjection={true}
				/>
			</div>
```
 (I've originally used more prop values, but shortened it down to the absolutely necessary for now to just get it working).

My project is a Typescript project, and the index.d.ts for the Cropper looks like this:

```
import React from 'react';
import { Area, MediaSize, Point, Size } from './types';
export declare type CropperProps = {
    image?: string;
...
};
declare type State = {
    cropSize: Size | null;
    hasWheelJustStarted: boolean;
};
declare class Cropper extends React.Component<CropperProps, State> {
    static defaultProps: {
        ... more props ....
    };
    ... more props ....
    render(): JSX.Element;
}
export default Cropper;
//# sourceMappingURL=index.d.ts.map
```

**Expected behaviour**

Any help with getting the component working would be massively appreciated! I must be doing some importing wrong...

**Comment by ValentinH** [comment] 2021-05-13 18:49
Are you sure that the issue is coming from this component? Here's a working example with Typescript: https://codesandbox.io/s/react-easy-crop-in-ts-lj1if

What else is in your `SummaryTab` component?

**Comment by NastiaPev** [comment] 2021-05-14 11:04
Hi Valentin! Thank you so much for getting back to me. The issue is definitely with the cropper as when the cropper component is commented out and no other changes are made, the page works fine.
 common.bundle.js contains the cropper code if that's helpful. 
Do I need to do any separate types installation maybe?

**Comment by ValentinH** [comment] 2021-05-14 13:37
Actually, when you say:
> the index.d.ts for the Cropper looks like this

did you manually add this file to your project?

**Comment by ValentinH** [comment] 2021-06-03 18:02
Closing as there was no answer for a while. Comment to re-open 😉

**Closed by ValentinH** 2021-06-03 18:02 UTC
