### ISSUE TITLE
Bug when trying to crop SVG on Mozilla

### ISSUE THREAD

**Issue by edoudou** [ricardo-ch/react-easy-crop#76] opened 2019-12-04 11:13 UTC
## Bug when trying to crop SVG on Mozilla

Use the crop on a SVG image using Firefox (didn't identify the exact condition right now, I'm on a fixed div for what it's worth).

  **Observed behaviour:** In OnImageLoaded callback parameter, imageSize.naturalHeight and imageSize.naturalWidth is equal 0.

  **Expected behaviour:** In OnImageLoaded callback parameter, imageSize.naturalHeight and imageSize.naturalWidth is equal to the natural size of svg.

Right now, it is not a pain point for me as I have found a solution to work around it.
How ever, the bug did not occurred when trying it on codesandbox, so it might be the case only in a specific case that I did not identify yet.

Here is my attempt to reproduce the bug, so you have more info of what I was trying to do. https://codesandbox.io/s/react-easy-crop-demo-nw5es

Just wanted you to know it might be an issue for someone else, if you want to close the issue now I'll understand.

**Comment by ValentinH** [comment] 2019-12-04 11:32
Thanks for the clear description, I'll have a look :)

**Comment by ValentinH** [comment] 2019-12-04 12:24
Indeed, I've tested it both on Brave and Firefox and could not reproduce.

I'm closing for now, but feel free to re-open if you manage to have a reproductible scenario :)

**Closed by ValentinH** 2019-12-04 12:24 UTC
