### ISSUE TITLE
canvas is black in IPhone 8

### ISSUE THREAD

**Issue by a-m-dev** [ricardo-ch/react-easy-crop#98] opened 2020-02-17 10:50 UTC
hi there , tnx for creating this really awesome package

as much as i use this great pkg, i really love i but i had faced with 2 issue for almost in passed five days, every thing is awesome in android phone except:

SAMSUNG A30
----
only issue is that picture is 90 degree rotated even by using `rotation = 0`

iPhone 8
----
just because that iphone tooks pictures around 4k resolution i have an warning in my console in safari that its more than allocated memory to create canvas for that resolution, i think that at the first level it is because of image resolution and at the second its because of the safe area that we create to crop image

 there for the canvas (i.e. 1000x1000px) is created , but it is black! and when i', converting it to blob to wire it trough api, it just sends a black image...

please help!

**Comment by ValentinH** [comment] 2020-02-17 13:56
For the Samsung issue, it's the same as https://github.com/ricardo-ch/react-easy-crop/issues/95

For iOS, this is a known issue and you need to make the canvas smaller.

**Comment by a-m-dev** [comment] 2020-02-17 13:57
even by testing [https://codesandbox.io/s/y09komm059](this) codesandbox sample you provided in iPhone 8 the canvas is black and my logs says this: 

`Canvas Area exceeds the maximum limit (width * height > 16777216)`

**Comment by a-m-dev** [comment] 2020-02-17 13:59
how can i make the canvas smaller? any hint ? to preserve aspect ration and not cut image that contains black parts??
any code snippet would be appreciated!

**Comment by ValentinH** [comment] 2020-02-17 14:26
You can use something like this https://github.com/nodeca/pica to resize the image before cropping it.

Canvas manipulations are tricky and are not supported by this library. When I see the bugs that are becoming frequent with latest iphones, I'm happy I didn't implement that as part of this library.

I'm sorry but I can't help you more than telling you to either update the canvas handling example (make it smaller somehow) or use another library to resize the image before cropping it.

**Comment by ValentinH** [comment] 2020-02-20 20:08
I'm closing this as this is not a bug or something that can be done as part of the library.

**Closed by ValentinH** 2020-02-20 20:08 UTC
