### ISSUE TITLE
Cropped image is getting black full image in iphone mobiles

### ISSUE THREAD

**Issue by vinodtana1** [ricardo-ch/react-easy-crop#207] opened 2021-02-02 10:21 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

- Please create a CodeSandbox that demonstrates your issue. You can fork the Basic example: https://codesandbox.io/s/react-easy-crop-v69ly910ql.

**Comment by vinodtana1** [comment] 2021-02-02 10:23
same image cropping is working fine in chrome and all devices 
but in iphone mobiles cropped image is getting black color

**Comment by ValentinH** [comment] 2021-02-02 11:46
Duplicate of many issues regarding ios and black output. Please use the search tool.

**Closed by ValentinH** 2021-02-02 11:46 UTC
