### ISSUE TITLE
cropped area pixels do not match when image is rotated

### ISSUE THREAD

**Issue by Eriickson** [ricardo-ch/react-easy-crop#273] opened 2021-06-26 18:24 UTC
When I rotate the image, the coordinates provided by this library are not correct

## original image
![0_qX9Z04djA3Oo02Wh](https://user-images.githubusercontent.com/38663299/123522088-23895b00-d689-11eb-93c1-52c40720a2df.jpeg)

## Coordinates it should have when the image is rotated 90 degrees
```width: 2896```, ```height: 2896```, ```x: 1448```, ```y: 0```

![image](https://user-images.githubusercontent.com/38663299/123522114-4a479180-d689-11eb-9efb-78a6c740ee62.png)

## Coordinates it gives me when the image is rotated 90 degrees
```width: 2896```, ```height: 2896```, ```x: 727```, ```y: 726```
![image](https://user-images.githubusercontent.com/38663299/123522193-db1e6d00-d689-11eb-8001-591a26f73a80.png)

## in the same way when the broken 270 degrees there are values ​​that give me negative
![image](https://user-images.githubusercontent.com/38663299/123522253-36e8f600-d68a-11eb-9abe-be953e125846.png)

**Comment by ValentinH** [comment] 2021-06-26 19:17
I think this is a duplicate of https://github.com/ricardo-ch/react-easy-crop/issues/240

**Comment by ValentinH** [comment] 2021-08-24 10:13
Closing as there was no answer for a while. Comment to re-open 😉

**Closed by ValentinH** 2021-08-24 10:13 UTC
