### ISSUE TITLE
iphone image exif orientation

### ISSUE THREAD

**Issue by formidable255** [ricardo-ch/react-easy-crop#95] opened 2020-02-07 09:57 UTC
With pictures uploaded from iphone, there's exif data specifying the orientation of the image. It seems this data is not preserved after cropping the image. Are there any solutions to this?

**Comment by ValentinH** [comment] 2020-02-07 14:12
Indeed, this library does not do anything regarding EXIF data.

However, you can rotate the image before passing it to the cropper.

For instance, if you check this sandbox (https://codesandbox.io/s/y09komm059), you could add some logic in the `readFile()` function in order to rotate the image. At work, we use this package (https://github.com/mooyoul/get-orientation) to retrieve the orientation and we then rotate the image using a canvas operation.

**Comment by formidable255** [comment] 2020-02-07 17:37
On an iphone, it seems to be able to detect orientation on its own and displays the image correctly. However, after cropping, it seems to crop the wrong area and the image returned is oriented differently than what was displayed.

On Android or pc, the image is oriented incorrectly but at least when i do crop it, it returns exactly what is cropped.

Any insight on whats happening with cropping on iphone?

**Comment by ValentinH** [comment] 2020-02-07 20:01
I don't have an iPhone so I cannot reproduce this, but this is weird indeed.

Could you try this demo on an iPhone to see if the rotation is correctly handled: https://mooyoul.github.io/get-orientation/ ?

**Comment by formidable255** [comment] 2020-02-07 20:12
I tried that on iphone chrome and android chrome.

For iPhone, both the images(original and rotated) are correctly oriented and there is an acknowledged rotation.

For android, original image is incorrectly oriented and then corrected in the rotated photo.

**Comment by ValentinH** [comment] 2020-02-07 20:16
This is good news, it means that the library correctly handle both Android and iPhone! 

So if you use it when creating the image dataUrl in the function I linked above, it will work fine :)

**Comment by formidable255** [comment] 2020-02-07 21:08
Just to confirm, after cropping, the exif data is no longer existent in the new dataUrl?

If that's the case then i shouldn't need to worry about rotating images that ive already cropped since its already been handled.

**Comment by ValentinH** [comment] 2020-02-07 21:12
I'm not sure about this, I don't know much about exif.

**Comment by ValentinH** [comment] 2020-02-08 10:41
@formidable255 I've updated the [demo with image input](https://codesandmbox.io/s/winter-pine-y09komm059) and it now automatically rotates the image if needed. 

Tested on Android, please tell me if it works fine on iphone. 🙂

**Comment by formidable255** [comment] 2020-02-10 10:05
Works fine for iphone, thanks!

**Comment by ValentinH** [comment] 2020-02-10 10:07
Great! Can we close this issue now?

**Closed** 2020-02-10 10:22 UTC
